/*
 * MIT License
 * 
 * Copyright (c) 2023 Can Joshua Lehmann
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

// Autogenerated instruction decoder, see gen_decoder.py

typedef enum {
  <<opcode>>
} opcode_t;

const char* OPCODE_NAMES[] = {
  <<names>>
};

typedef uint8_t reg_t;

typedef struct {
  opcode_t opcode;
  reg_t rd;
  reg_t rs1;
  reg_t rs2;
  uint32_t imm;
} inst_t;

uint32_t nbits(uint32_t n) {
  return n >= 32 ? ~0 : (1 << n) - 1;
}

uint32_t s_ext(uint32_t value, unsigned sign_bit) {
  return value & (1 << sign_bit) ? value | ~nbits(sign_bit) : value;
}

uint32_t decode_imm20(uint32_t inst) {
  return inst & ~2047;
}

uint32_t decode_imm12(uint32_t inst) {
  return s_ext((inst >> 20) & nbits(12), 11);
}

uint32_t decode_jimm20(uint32_t inst) {
  uint32_t imm = 0;
  imm |= ((inst >> 12) & nbits(8)) << 12;
  imm |= ((inst >> 20) & nbits(1)) << 11;
  imm |= ((inst >> 21) & nbits(10)) << 1;
  imm |= ((inst >> 31) & nbits(1)) << 20;
  return s_ext(imm, 20);
}

uint32_t decode_bimm12_lo_hi(uint32_t inst) {
  uint32_t imm = 0;
  imm |= ((inst >> 8) & nbits(4)) << 1;
  imm |= ((inst >> 25) & nbits(6)) << 5;
  imm |= ((inst >> 7) & nbits(1)) << 11;
  imm |= ((inst >> 31) & nbits(1)) << 12;
  return s_ext(imm, 12);
}

uint32_t decode_imm12_lo_hi(uint32_t inst) {
  uint32_t imm = 0;
  imm |= ((inst >> 7) & nbits(5)) << 0;
  imm |= ((inst >> 25) & nbits(7)) << 5;
  return s_ext(imm, 11);
}

int decode(uint32_t inst, inst_t* decoded) {
  #define CASE(mask, pattern, instruction) \
    if ((inst & mask) == pattern) { \
      *decoded = instruction; \
      return 0; \
    }
  
  <<decode>>
  
  #undef CASE
  
  return 1;
}
