/*
 * MIT License
 * 
 * Copyright (c) 2023 Can Joshua Lehmann
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

// Autogenerated instruction decoder, see gen_decoder.py

typedef enum {
  ADD, ADDI, AND, ANDI, AUIPC, BEQ, BGE, BGEU, BLT, BLTU, BNE, EBREAK, ECALL, FENCE, JAL, JALR, LB, LBU, LH, LHU, LUI, LW, OR, ORI, SB, SH, SLL, SLT, SLTI, SLTIU, SLTU, SRA, SRL, SUB, SW, XOR, XORI
} opcode_t;

const char* OPCODE_NAMES[] = {
  "ADD", "ADDI", "AND", "ANDI", "AUIPC", "BEQ", "BGE", "BGEU", "BLT", "BLTU", "BNE", "EBREAK", "ECALL", "FENCE", "JAL", "JALR", "LB", "LBU", "LH", "LHU", "LUI", "LW", "OR", "ORI", "SB", "SH", "SLL", "SLT", "SLTI", "SLTIU", "SLTU", "SRA", "SRL", "SUB", "SW", "XOR", "XORI"
};

typedef uint8_t reg_t;

typedef struct {
  opcode_t opcode;
  reg_t rd;
  reg_t rs1;
  reg_t rs2;
  uint32_t imm;
} inst_t;

uint32_t nbits(uint32_t n) {
  return n >= 32 ? ~0 : (1 << n) - 1;
}

uint32_t s_ext(uint32_t value, unsigned sign_bit) {
  return value & (1 << sign_bit) ? value | ~nbits(sign_bit) : value;
}

uint32_t decode_imm20(uint32_t inst) {
  return inst & ~2047;
}

uint32_t decode_imm12(uint32_t inst) {
  return s_ext((inst >> 20) & nbits(12), 11);
}

uint32_t decode_jimm20(uint32_t inst) {
  uint32_t imm = 0;
  imm |= ((inst >> 12) & nbits(8)) << 12;
  imm |= ((inst >> 20) & nbits(1)) << 11;
  imm |= ((inst >> 21) & nbits(10)) << 1;
  imm |= ((inst >> 31) & nbits(1)) << 20;
  return s_ext(imm, 20);
}

uint32_t decode_bimm12_lo_hi(uint32_t inst) {
  uint32_t imm = 0;
  imm |= ((inst >> 8) & nbits(4)) << 1;
  imm |= ((inst >> 25) & nbits(6)) << 5;
  imm |= ((inst >> 7) & nbits(1)) << 11;
  imm |= ((inst >> 31) & nbits(1)) << 12;
  return s_ext(imm, 12);
}

uint32_t decode_imm12_lo_hi(uint32_t inst) {
  uint32_t imm = 0;
  imm |= ((inst >> 7) & nbits(5)) << 0;
  imm |= ((inst >> 25) & nbits(7)) << 5;
  return s_ext(imm, 11);
}

int decode(uint32_t inst, inst_t* decoded) {
  #define CASE(mask, pattern, instruction) \
    if ((inst & mask) == pattern) { \
      *decoded = instruction; \
      return 0; \
    }
  
  CASE(127, 55, ((inst_t){ .opcode = LUI, .rd = (inst >> 7) & 31, .imm = decode_imm20(inst) }));
  CASE(127, 23, ((inst_t){ .opcode = AUIPC, .rd = (inst >> 7) & 31, .imm = decode_imm20(inst) }));
  CASE(127, 111, ((inst_t){ .opcode = JAL, .rd = (inst >> 7) & 31, .imm = decode_jimm20(inst) }));
  CASE(28799, 103, ((inst_t){ .opcode = JALR, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 99, ((inst_t){ .opcode = BEQ, .imm = decode_bimm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 4195, ((inst_t){ .opcode = BNE, .imm = decode_bimm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 16483, ((inst_t){ .opcode = BLT, .imm = decode_bimm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 20579, ((inst_t){ .opcode = BGE, .imm = decode_bimm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 24675, ((inst_t){ .opcode = BLTU, .imm = decode_bimm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 28771, ((inst_t){ .opcode = BGEU, .imm = decode_bimm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 3, ((inst_t){ .opcode = LB, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 4099, ((inst_t){ .opcode = LH, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 8195, ((inst_t){ .opcode = LW, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 16387, ((inst_t){ .opcode = LBU, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 20483, ((inst_t){ .opcode = LHU, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 35, ((inst_t){ .opcode = SB, .imm = decode_imm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 4131, ((inst_t){ .opcode = SH, .imm = decode_imm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 8227, ((inst_t){ .opcode = SW, .imm = decode_imm12_lo_hi(inst), .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 19, ((inst_t){ .opcode = ADDI, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 8211, ((inst_t){ .opcode = SLTI, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 12307, ((inst_t){ .opcode = SLTIU, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 16403, ((inst_t){ .opcode = XORI, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 24595, ((inst_t){ .opcode = ORI, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(28799, 28691, ((inst_t){ .opcode = ANDI, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .imm = decode_imm12(inst) }));
  CASE(4261441663, 51, ((inst_t){ .opcode = ADD, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 1073741875, ((inst_t){ .opcode = SUB, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 4147, ((inst_t){ .opcode = SLL, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 8243, ((inst_t){ .opcode = SLT, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 12339, ((inst_t){ .opcode = SLTU, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 16435, ((inst_t){ .opcode = XOR, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 20531, ((inst_t){ .opcode = SRL, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 1073762355, ((inst_t){ .opcode = SRA, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 24627, ((inst_t){ .opcode = OR, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(4261441663, 28723, ((inst_t){ .opcode = AND, .rd = (inst >> 7) & 31, .rs1 = (inst >> 15) & 31, .rs2 = (inst >> 20) & 31 }));
  CASE(28799, 15, ((inst_t){ .opcode = FENCE, .rs1 = (inst >> 15) & 31, .rd = (inst >> 7) & 31 }));
  CASE(4294967295, 115, ((inst_t){ .opcode = ECALL }));
  CASE(4294967295, 1048691, ((inst_t){ .opcode = EBREAK }));
  
  #undef CASE
  
  return 1;
}
